
Error: Can't open display: 
Traceback (most recent call last):
  File "/home/pi/git/RPI_Projector/python_script/main.py", line 27, in <module>
    time.sleep(0.3)
KeyboardInterrupt
Error: Can't open display: 
Traceback (most recent call last):
  File "/home/pi/git/RPI_Projector/python_script/main.py", line 27, in <module>
    time.sleep(0.3)
KeyboardInterrupt
Error: Can't open display: 
Error: Can't open display: 
Error: Can't open display: 
